### PR TITLE
Add a (Contributor Covenant) CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by patricekrakow**
This PR is to add a *Contributor Covenant* CODE_OF_CONDUCT.md to our repository. You can find details about *Contributor Covenant* at <https://www.contributor-covenant.org/>. I have put the email of Erasmus, which you can already find at exposed on the <http://www.papinet.org/contact/> page, as the contact to report complaints.

### CODE REVIEW

**Comment by patricekrakow** [comment]
Please **wait** for the confirmation from Erasmus that it is OK to use his email as contact to report complaints, **before** approving this PR.

**Comment by tommeniga** [comment]
I suggest we call it report@papinet.org

**Comment by patricekrakow** [comment]
@tommeniga will look at it.

**Comment by patricekrakow** [comment]
I will close this PR, if we want to add a `CODE_OF_CONDUCT.md` it will be easier to start from scratch instead of resolving the conflicts.

**Pull request closed without merging**
